#!/bin/bash
echo starting batch job initialization

EL_JOBID=$(printf "%06d" $1)
RANDOMSEED=$(($1 + 1))
NEVENTS=1000
SKIPEVENTS=$(($1 * $NEVENTS))
FIRSTEVENT=$(($SKIPEVENTS + 1))
THERUNNUMBER=999999

# The job-option python file, and the working directory
THEJO=$2
THEDIR=$3

TMP=${THEJO/mc\./mc_13TeV\.}
THEGRIDPACK=${TMP/\.py/\.GRID\.tar\.gz}
THEGRIDPACKDIR=${THEDIR/batchFrom/make}

# Set up ATLAS, athena
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
alias 'setupATLAS=source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh    

# Test to make sure that the gridpack exists!
echo  -e ${GREEN} Checking for Gridpack ../$THEGRIDPACKDIR/$THEGRIDPACK ${NC};
if [ ! -f ../$THEGRIDPACKDIR/$THEGRIDPACK ]; then
    echo  -e ${GREEN} Could not find Gridpack ../$THEGRIDPACKDIR/$THEGRIDPACK. Stopping. ${NC};
else

    export THEJOBDIR=job$EL_JOBID
    mkdir -p $THEJOBDIR/$THERUNNUMBER

    cd $THEJOBDIR/$THERUNNUMBER;
    ln -s ../../../$THEJO .
    ln -s ../../../$THEGRIDPACKDIR/$THEGRIDPACK .
    cd -;

    echo -e ${GREEN} Running Gen_tf.py, using existing gridpack. ${NC};
    cd $THEJOBDIR;

    asetup AthGeneration,21.6.73,64,here
    export PYTHONPATH=`pwd`:$PYTHONPATH

    echo -e ${GREEN} Running from directory ${PWD} ${NC};
    echo RANDOMSEED: $RANDOMSEED
    echo NEVENTS : $NEVENTS
    echo SKIPEVENTS: $SKIPEVENTS
    echo FIRSTEVENT: $FIRSTEVENT
    echo THERUNNUMBER: $THERUNNUMBER
    echo THEJO: $THEJO
    echo PYTHON: $(which python)
    echo ROOT: $(which root)
    env
    echo THEGRIDPACK: $THEGRIDPACK

    Gen_tf.py --ecmEnergy=13000 --firstEvent=$FIRSTEVENT --jobConfig=$THERUNNUMBER\
      --outputEVNTFile=EVNT.root --randomSeed=$RANDOMSEED --maxEvents=$NEVENTS

    echo done.
fi;

echo -e ${GREEN} Finished. ${NC};
